1. Clean all configuration related to intersect.org.au   - admin, notification sender related: production(steve.cassidy@mq.edu.au), others(karl.li@mq.edu.au)   - staging config related: change to sol1.net   - test (spec, feature) related: change to alveo.edu.au 2. Fix Collection.text nil issue 3. Upgrade select2-rails gem to 4.0.3 to fix "TypeError: element.select2 is not a function" issue